
  [[main]]
  name = "About"
  weight = 100
  identifier = "about"
  url = "#about"

  [[main]]
  name = "Research"
  weight = 200
  identifier = "research"
  url = "#research"

  [[main]]
  name = "Conference Talks"
  weight = 300
  identifier = "conference"
  url = "#conference-talks"

  # [[main]]
  # name = "Publications"
  # weight = 400
  # identifier = "publications"
  # url = "/publications/"

  # [[main]]
  # name = "Accomplishments"
  # weight = 500
  # identifier = "accomplishments"

  # [[main]]
  # name = "Awards"
  # weight = 510
  # identifier = "awards"
  # url = "/awards/"
  # parent = "accomplishments"  

  # [[main]]
  # name = "Certifications"
  # weight = 520
  # identifier = "certifications"
  # url = "/certifications/"
  # parent = "accomplishments"

   # [[main]]
   # name = "Contact"
   # weight = 600
   # identifier = "contact"
   # url = "#contact"

  [[main]]
  name = "CV"
  weight = 400
  identifier = "cv"
  url = "/cv/cv.pdf"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"